// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.minimalapi.Core.Prod.Models;

#nullable disable

namespace backend.minimalapi.ui.Migrations.ProduitDb
{
    [DbContext(typeof(ProduitDbContext))]
    [Migration("20251202130903_UpdateBouteilleImage")]
    partial class UpdateBouteilleImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DbouteilleImage", b =>
                {
                    b.Property<int>("BouteilleImageId")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BouteilleImageId"));

                    b.Property<int>("BouteilleId")
                        .HasColumnType("int");

                    b.Property<int?>("DbouteilleBouteilleId")
                        .HasColumnType("int");

                    b.Property<string>("ImageDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BouteilleImageId");

                    b.HasIndex("DbouteilleBouteilleId");

                    b.ToTable("DbouteilleImages");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DbouteilleImage", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.Dbouteille", null)
                        .WithMany("DbouteilleImages")
                        .HasForeignKey("DbouteilleBouteilleId");
                });

#pragma warning restore 612, 618
        }
    }
}
