// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.minimalapi.Core.Prod.Models;

#nullable disable

namespace backend.minimalapi.ui.Migrations.ProduitDb
{
    [DbContext(typeof(ProduitDbContext))]
    [Migration("20250712130903_InitProduit")]
    partial class InitProduit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dbouteille", b =>
                {
                    b.Property<int>("BouteilleId")
                        .HasColumnType("int");

                    b.Property<int>("Capacité")
                        .HasColumnType("int");

                    b.Property<int>("CuvéeId")
                        .HasColumnType("int");

                    b.Property<int?>("DcuvéeCuvéeId")
                        .HasColumnType("int");

                    b.Property<string>("LibelléBouteille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BouteilleId");

                    b.HasIndex("DcuvéeCuvéeId");

                    b.ToTable("Dbouteilles");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DbouteilleImage", b =>
                {
                    b.Property<int>("BouteilleImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BouteilleImageId"));

                    b.Property<int>("BouteilleId")
                        .HasColumnType("int");

                    b.Property<int?>("DbouteilleBouteilleId")
                        .HasColumnType("int");

                    b.Property<string>("ImageDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BouteilleImageId");

                    b.HasIndex("DbouteilleBouteilleId");

                    b.ToTable("DbouteilleImages");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DcommandesClient", b =>
                {
                    b.Property<long>("CommandeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFacturation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<string>("GesteCommercial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdContactFacturation")
                        .HasColumnType("int");

                    b.Property<int>("IdContactLivraison")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantCommande")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatutCommande")
                        .HasColumnType("int");

                    b.HasKey("CommandeId");

                    b.ToTable("DcommandesClients");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dcuvée", b =>
                {
                    b.Property<int>("CuvéeId")
                        .HasColumnType("int");

                    b.Property<int>("AnnéeCuvée")
                        .HasColumnType("int");

                    b.Property<string>("LibelléCuvée")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCuvée")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CuvéeId");

                    b.ToTable("Dcuvées");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DdescriptionCuvée", b =>
                {
                    b.Property<int>("DescriptionCuvéeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescriptionCuvéeId"));

                    b.Property<int>("CuvéeId")
                        .HasColumnType("int");

                    b.Property<int?>("DcuvéeCuvéeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionLongue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Langue")
                        .HasColumnType("int");

                    b.HasKey("DescriptionCuvéeId");

                    b.HasIndex("DcuvéeCuvéeId");

                    b.ToTable("DdescriptionCuvées");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dlangue", b =>
                {
                    b.Property<int>("LangueId")
                        .HasColumnType("int");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LangueId");

                    b.ToTable("Dlangues");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DlignesCommande", b =>
                {
                    b.Property<long>("LignesCommandeId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommandeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DcommandesClientCommandeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FraisLivraison")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantLigne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NuméroLigne")
                        .HasColumnType("int");

                    b.Property<long>("ProduitId")
                        .HasColumnType("bigint");

                    b.Property<short>("QuantitéProduit")
                        .HasColumnType("smallint");

                    b.Property<short>("SoldeQuantitéProduit")
                        .HasColumnType("smallint");

                    b.HasKey("LignesCommandeId");

                    b.HasIndex("DcommandesClientCommandeId");

                    b.ToTable("DlignesCommandes");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dproduit", b =>
                {
                    b.Property<long>("ProduitId")
                        .HasColumnType("bigint");

                    b.Property<int>("BouteilleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatePeremption")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DbouteilleBouteilleId")
                        .HasColumnType("int");

                    b.Property<decimal>("FraisPoste")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LibelléProduit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("NombreBouteilles")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PrixTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("QuantitéMinimum")
                        .HasColumnType("smallint");

                    b.HasKey("ProduitId");

                    b.HasIndex("DbouteilleBouteilleId");

                    b.ToTable("Dproduits");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DproduitAction", b =>
                {
                    b.Property<int>("ProduitActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduitActionId"));

                    b.Property<string>("ActionDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActionPourcent")
                        .HasColumnType("int");

                    b.Property<long?>("DproduitProduitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DébutAction")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinAction")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProduitId")
                        .HasColumnType("bigint");

                    b.HasKey("ProduitActionId");

                    b.HasIndex("DproduitProduitId");

                    b.ToTable("DproduitActions");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dstock", b =>
                {
                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("BouteilleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEntrée")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DbouteilleBouteilleId")
                        .HasColumnType("int");

                    b.Property<int>("QuantitéEntrée")
                        .HasColumnType("int");

                    b.Property<int>("QuantitéRéserve")
                        .HasColumnType("int");

                    b.Property<int>("QuantitéSolde")
                        .HasColumnType("int");

                    b.Property<decimal>("ValeurEntrée")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurSolde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurVendue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockId");

                    b.HasIndex("DbouteilleBouteilleId");

                    b.ToTable("Dstocks");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dbouteille", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.Dcuvée", null)
                        .WithMany("Dbouteilles")
                        .HasForeignKey("DcuvéeCuvéeId");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DbouteilleImage", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.Dbouteille", null)
                        .WithMany("DbouteilleImages")
                        .HasForeignKey("DbouteilleBouteilleId");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DdescriptionCuvée", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.Dcuvée", null)
                        .WithMany("DdescriptionCuvées")
                        .HasForeignKey("DcuvéeCuvéeId");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DlignesCommande", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.DcommandesClient", null)
                        .WithMany("DlignesCommandes")
                        .HasForeignKey("DcommandesClientCommandeId");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dproduit", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.Dbouteille", null)
                        .WithMany("Dproduits")
                        .HasForeignKey("DbouteilleBouteilleId");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DproduitAction", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.Dproduit", null)
                        .WithMany("DproduitActions")
                        .HasForeignKey("DproduitProduitId");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dstock", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Prod.Models.Dbouteille", null)
                        .WithMany("Dstocks")
                        .HasForeignKey("DbouteilleBouteilleId");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dbouteille", b =>
                {
                    b.Navigation("DbouteilleImages");

                    b.Navigation("Dproduits");

                    b.Navigation("Dstocks");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.DcommandesClient", b =>
                {
                    b.Navigation("DlignesCommandes");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dcuvée", b =>
                {
                    b.Navigation("Dbouteilles");

                    b.Navigation("DdescriptionCuvées");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Prod.Models.Dproduit", b =>
                {
                    b.Navigation("DproduitActions");
                });
#pragma warning restore 612, 618
        }
    }
}
