// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.minimalapi.Core.Cli.Models;

#nullable disable

namespace backend.minimalapi.ui.Migrations.ClientDb
{
    [DbContext(typeof(ClientDbContext))]
    [Migration("20250405142230_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.minimalapi.Core.Cli.Models.Dclient", b =>
                {
                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateContact")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prénom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Dclients");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Cli.Models.Dcontact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Adresse1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adresse2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientIdNavigationClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cnom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cprénom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("DtypeContactId")
                        .HasColumnType("smallint");

                    b.Property<int?>("NuméroPostal")
                        .HasColumnType("int");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TélFixe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TélPortable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("ClientIdNavigationClientId");

                    b.ToTable("Dcontacts");
                });

            modelBuilder.Entity("backend.minimalapi.Core.Cli.Models.Dcontact", b =>
                {
                    b.HasOne("backend.minimalapi.Core.Cli.Models.Dclient", "ClientIdNavigation")
                        .WithMany()
                        .HasForeignKey("ClientIdNavigationClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientIdNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
